### ISSUE TITLE
Cannot make AAB (bundle)🐛 

### ISSUE THREAD

**Issue by silenteyesoncode** [100mslive/100ms-react-native#1398]
### Description

```
> Task :app:bundleReleaseJsAndAssets
Execution optimizations have been disabled for task ':app:bundleReleaseJsAndAssets' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/macos/Documents/GitHub/reactnative_meradoc'. Reason: Task ':app:bundleReleaseJsAndAssets' uses this output of task ':100mslive_react-native-hms:compileReleaseLibraryResources' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/macos/Documents/GitHub/reactnative_meradoc'. Reason: Task ':app:bundleReleaseJsAndAssets' uses this output of task ':100mslive_react-native-hms:compileReleaseRenderscript' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/macos/Documents/GitHub/reactnative_meradoc'. Reason: Task ':app:bundleReleaseJsAndAssets' uses this output of task ':100mslive_react-native-hms:generateReleaseResValues' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/macos/Documents/GitHub/reactnative_meradoc'. Reason: Task ':app:bundleReleaseJsAndAssets' uses this output of task ':100mslive_react-native-hms:packageReleaseResources' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/macos/Documents/GitHub/reactnative_meradoc'. Reason: Task ':app:bundleReleaseJsAndAssets' uses this output of task ':@100mslive_react-native-hms:compileReleaseLibraryResources' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/macos/Documents/GitHub/reactnative_meradoc'. Reason: Task ':app:bundleReleaseJsAndAssets' uses this output of task ':@100mslive_react-native-hms:compileReleaseRenderscript' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/macos/Documents/GitHub/reactnative_meradoc'. Reason: Task ':app:bundleReleaseJsAndAssets' uses this output of task ':@100mslive_react-native-hms:generateReleaseResValues' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/macos/Documents/GitHub/reactnative_meradoc'. Reason: Task ':app:bundleReleaseJsAndAssets' uses this output of task ':@100mslive_react-native-hms:packageReleaseResources' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.
warning: the transform cache was reset.
                    Welcome to Metro!
              Fast - Scalable - Integrated


watchman warning:  Recrawled this watch 1 time, most recently because:
MustScanSubDirs UserDroppedTo resolve, please review the information on
https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
To clear this warning, run:
`watchman watch-del '/Users/macos/Documents/GitHub/reactnative_meradoc' ; watchman watch-project '/Users/macos/Documents/GitHub/reactnative_meradoc'`

Recrawled this watch 1 time, most recently because:
MustScanSubDirs UserDroppedTo resolve, please review the information on
https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
To clear this warning, run:
`watchman watch-del '/Users/macos/Documents/GitHub/reactnative_meradoc' ; watchman watch-project '/Users/macos/Documents/GitHub/reactnative_meradoc'`

Recrawled this watch 1 time, most recently because:
MustScanSubDirs UserDroppedTo resolve, please review the information on
https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
To clear this warning, run:
`watchman watch-del '/Users/macos/Documents/GitHub/reactnative_meradoc' ; watchman watch-project '/Users/macos/Documents/GitHub/reactnative_meradoc'`

Failed to construct transformer:  Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:79:19)
    at Object.createHash (node:crypto:139:10)
    at stableHash (/Users/macos/Documents/GitHub/reactnative_meradoc/node_modules/metro-cache/src/stableHash.js:19:8)
    at Object.getCacheKey (/Users/macos/Documents/GitHub/reactnative_meradoc/node_modules/metro-transform-worker/src/index.js:593:7)
    at getTransformCacheKey (/Users/macos/Documents/GitHub/reactnative_meradoc/node_modules/metro/src/DeltaBundler/getTransformCacheKey.js:24:19)
    at new Transformer (/Users/macos/Documents/GitHub/reactnative_meradoc/node_modules/metro/src/DeltaBundler/Transformer.js:48:9)
    at /Users/macos/Documents/GitHub/reactnative_meradoc/node_modules/metro/src/Bundler.js:22:29
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  opensslErrorStack: [
    'error:03000086:digital envelope routines::initialization error',
    'error:0308010C:digital envelope routines::unsupported'
  ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
error Cannot read properties of undefined (reading 'transformFile').
TypeError: Cannot read properties of undefined (reading 'transformFile')
    at Bundler.transformFile (/Users/macos/Documents/GitHub/reactnative_meradoc/node_modules/metro/src/Bundler.js:48:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.transform (/Users/macos/Documents/GitHub/reactnative_meradoc/node_modules/metro/src/lib/transformHelpers.js:101:12)
    at async processModule (/Users/macos/Documents/GitHub/reactnative_meradoc/node_modules/metro/src/DeltaBundler/traverseDependencies.js:137:18)
    at async traverseDependenciesForSingleFile (/Users/macos/Documents/GitHub/reactnative_meradoc/node_modules/metro/src/DeltaBundler/traverseDependencies.js:131:3)
    at async Promise.all (index 0)
    at async initialTraverseDependencies (/Users/macos/Documents/GitHub/reactnative_meradoc/node_modules/metro/src/DeltaBundler/traverseDependencies.js:114:3)
    at async DeltaCalculator._getChangedDependencies (/Users/macos/Documents/GitHub/reactnative_meradoc/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:164:25)
    at async DeltaCalculator.getDelta (/Users/macos/Documents/GitHub/reactnative_meradoc/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:94:16)
    at async DeltaBundler.buildGraph (/Users/macos/Documents/GitHub/reactnative_meradoc/node_modules/metro/src/DeltaBundler.js:50:5)
info Run CLI with --verbose flag for more details.

> Task :app:bundleReleaseJsAndAssets FAILED

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'node'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':100mslive_react-native-hms:compileReleaseLibraryResources'.
> A failure occurred while executing com.android.build.gradle.tasks.CompileLibraryResourcesTask$CompileLibraryResourcesAction
   > There were multiple failures while executing work items
      > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
         > Android resource compilation failed
           ERROR:AAPT: /Users/macos/Documents/GitHub/reactnative_meradoc/node_modules/@100mslive/react-native-hms/android/build/intermediates/packaged_res/release/drawable-ldpi-v4/ic_camera_toggle_on.png: error: file not found.
           
               
      > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
         > Android resource compilation failed
           ERROR:AAPT: /Users/macos/Documents/GitHub/reactnative_meradoc/node_modules/@100mslive/react-native-hms/android/build/intermediates/packaged_res/release/drawable-mdpi-v4/ic_camera_toggle_on.png: error: file not found.
           
               
      > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
         > Android resource compilation failed
           ERROR:AAPT: /Users/macos/Documents/GitHub/reactnative_meradoc/node_modules/@100mslive/react-native-hms/android/build/intermediates/packaged_res/release/drawable-hdpi-v4/ic_camera_toggle_on.png: error: file not found.
           
               
      > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
         > Android resource compilation failed
           ERROR:AAPT: /Users/macos/Documents/GitHub/reactnative_meradoc/node_modules/@100mslive/react-native-hms/android/build/intermediates/packaged_res/release/drawable-ldpi-v4/ic_camera_toggle_off.png: error: file not found.
           
               
      > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
         > Android resource compilation failed
           ERROR:AAPT: /Users/macos/Documents/GitHub/reactnative_meradoc/node_modules/@100mslive/react-native-hms/android/build/intermediates/packaged_res/release/drawable-mdpi-v4/ic_camera_toggle_off.png: error: file not found.
           
               
      > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
         > Android resource compilation failed
           ERROR:AAPT: /Users/macos/Documents/GitHub/reactnative_meradoc/node_modules/@100mslive/react-native-hms/android/build/intermediates/packaged_res/release/drawable-xhdpi-v4/ic_camera_toggle_on.png: error: file not found.
           
               
      > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
         > Android resource compilation failed
           ERROR:AAPT: /Users/macos/Documents/GitHub/reactnative_meradoc/node_modules/@100mslive/react-native-hms/android/build/intermediates/packaged_res/release/drawable-xxhdpi-v4/ic_camera_toggle_on.png: error: file not found.
           
               
      > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
         > Android resource compilation failed
           ERROR:AAPT: /Users/macos/Documents/GitHub/reactnative_meradoc/node_modules/@100mslive/react-native-hms/android/build/intermediates/packaged_res/release/drawable-hdpi-v4/ic_camera_toggle_off.png: error: file not found.
           
               

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 2 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.
```

### 100ms React Native Version

1.10.6

### React Native Version

0.66.4

### Steps to reproduce

1. Install node mudules
2. Start project in android
3. Clean gradle 
4. Run ./gradlew bundleRelease

### Expected results

can successfully make AAB build

### Code example, screenshot, or link to a repository

<details>
<summary>Code sample</summary>

```js
```

{
  "name": "react_nativeMR",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "link": "react-native link",
    "test": "jest",
    "lint": "eslint .",
    "build:android": "react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res",
    "android:clean": "rm -rf ./android/app/src/main/res/drawable-mdpi/ && rm -rf ./android/app/src/main/res/raw/",
    "android:cleanBuild": "cd android && ./gradlew clean",
    "build:devAndroid": "cd android && ./gradlew clean && ./gradlew assembleRelease && cd .. && open android/app/build/outputs/apk/release",
    "build:prodAndroid": "cd android && ./gradlew clean && ./gradlew bundleRelease && cd .. && open android/app/build/outputs/bundle/release",
    "start:reset": "react-native start --reset-cache"
  },
  "dependencies": {
    "@100mslive/react-native-hms": "^1.10.5",
    "@miblanchard/react-native-slider": "^2.1.0",
    "@react-native-async-storage/async-storage": "^1.23.1",
    "@react-native-community/checkbox": "^0.5.9",
    "@react-native-community/cli-platform-ios": "^7.0.1",
    "@react-native-community/clipboard": "^1.2.3",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-community/netinfo": "^6.2.1",
    "@react-native-community/progress-bar-android": "^1.0.4",
    "@react-native-community/progress-view": "^1.3.1",
    "@react-native-community/push-notification-ios": "^1.10.1",
    "@react-native-firebase/app": "^14.12.0",
    "@react-native-firebase/auth": "^14.8.0",
    "@react-native-firebase/crashlytics": "^14.8.0",
    "@react-native-firebase/firestore": "14.12.0",
    "@react-native-firebase/messaging": "^14.8.0",
    "@react-native-picker/picker": "^2.2.1",
    "@react-navigation/bottom-tabs": "^6.2.0",
    "@react-navigation/native": "^6.0.8",
    "@react-navigation/native-stack": "^6.9.12",
    "@react-navigation/stack": "^6.1.1",
    "@twotalltotems/react-native-otp-input": "^1.3.7",
    "axios": "^0.21.4",
    "crypto-js": "^3.2.0",
    "fbjs": "^3.0.2",
    "force": "^0.0.3",
    "i": "^0.3.7",
    "lottie-ios": "^4.4.3",
    "moment": "^2.29.1",
    "npm": "^8.3.0",
    "prop-types": "^15.8.0",
    "react": "17.0.2",
    "react-native": "0.66.4",
    "react-native-actions-sheet": "^0.6.0",
    "react-native-actionsheet-cstm": "^1.0.1",
    "react-native-alert-notification": "^0.3.4",
    "react-native-animatable": "^1.3.3",
    "react-native-animated-dots-carousel": "^1.0.1",
    "react-native-animated-pagination-dots": "^0.1.72",
    "react-native-blink-view": "^0.0.6",
    "react-native-calendar-strip": "^2.2.6",
    "react-native-calendars": "^1.1293.0",
    "react-native-camera": "^4.2.1",
    "react-native-card-flip": "^1.0.7",
    "react-native-chart-kit": "^6.12.0",
    "react-native-cli": "^2.0.1",
    "react-native-config": "^1.4.5",
    "react-native-cool-speedometer": "^1.1.5",
    "react-native-dashed-progress": "^1.0.1",
    "react-native-datepicker": "^1.7.2",
    "react-native-device-info": "^10.2.0",
    "react-native-document-picker": "^8.0.0",
    "react-native-dotenv": "^2.6.2",
    "react-native-drawer": "^2.5.1",
    "react-native-drop-down-item": "^1.1.0",
    "react-native-dropdown-picker": "^5.3.0",
    "react-native-elements": "^3.4.2",
    "react-native-flash-message": "^0.3.1",
    "react-native-foreground-service": "^1.0.0",
    "react-native-fs": "^2.20.0",
    "react-native-geocoding": "^0.5.0",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-get-location": "^2.2.1",
    "react-native-gifted-charts": "^1.2.42",
    "react-native-google-places-autocomplete": "^2.5.1",
    "react-native-htmlview": "^0.16.0",
    "react-native-hyperlink": "^0.0.19",
    "react-native-image-base64": "^0.1.4",
    "react-native-image-crop-picker": "^0.37.3",
    "react-native-image-picker": "^4.7.3",
    "react-native-image-resizer": "^1.4.5",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-linking": "^0.0.0",
    "react-native-maps": "^1.15.1",
    "react-native-masonry-brick-list": "^1.0.3",
    "react-native-material-dropdown": "^0.11.1",
    "react-native-media-controls": "^2.3.0",
    "react-native-modal": "^13.0.1",
    "react-native-network-logger": "^1.15.0",
    "react-native-otp": "^1.0.0",
    "react-native-otp-textinput": "0.0.8",
    "react-native-pager-view": "^5.4.9",
    "react-native-paper": "^4.11.2",
    "react-native-pdf": "6.4.0",
    "react-native-permissions": "^3.3.1",
    "react-native-phone-call": "^1.0.9",
    "react-native-picker-select": "^8.0.4",
    "react-native-progress-circle": "^2.1.0",
    "react-native-push-notification": "^8.1.1",
    "react-native-razorpay": "^2.2.8",
    "react-native-reanimated": "^2.11.0",
    "react-native-responsive-fontsize": "^0.5.1",
    "react-native-responsive-screen": "^1.4.2",
    "react-native-restart": "^0.0.24",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-screens": "^3.15.0",
    "react-native-share": "^8.2.2",
    "react-native-simple-radio-button": "^2.7.4",
    "react-native-simple-toast": "^1.1.3",
    "react-native-slider": "^0.11.0",
    "react-native-snackbar": "^2.4.0",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-svg": "^12.1.1",
    "react-native-tab-view": "^3.1.1",
    "react-native-ui-lib": "^6.8.1",
    "react-native-vector-icons": "^9.0.0",
    "react-native-video": "^5.2.0",
    "react-native-video-controls": "^2.8.1",
    "react-native-video-player": "^0.12.0",
    "react-native-virtualized-view": "^0.1.5",
    "react-native-webview": "^11.17.1",
    "react-native-youtube-iframe": "^2.2.2",
    "react-navigation": "^4.0.10",
    "react-navigation-drawer": "^2.7.1",
    "react-navigation-stack": "^2.10.2",
    "react-navigation-tabs": "^2.10.1",
    "react-redux": "^7.2.6",
    "redux": "^4.1.2",
    "redux-persist": "^6.0.0",
    "redux-saga": "^1.1.3",
    "rn-fetch-blob": "^0.12.0",
    "simple-carousel-react-native": "^1.0.2"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.66.2",
    "react-test-renderer": "17.0.2"
  },
  "jest": {
    "preset": "react-native"
  },
  "packageManager": "yarn@3.6.4+sha512.e70835d4d6d62c07be76b3c1529cb640c7443f0fe434ef4b6478a5a399218cbaf1511b396b3c56eb03bc86424cff2320f6167ad2fde273aa0df6e60b7754029f"
}

### Logs

<details>
<summary>Logs</summary>

```console
> Task :app:bundleReleaseJsAndAssets
Execution optimizations have been disabled for task ':app:bundleReleaseJsAndAssets' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/macos/Documents/GitHub/reactnative_meradoc'. Reason: Task ':app:bundleReleaseJsAndAssets' uses this output of task ':100mslive_react-native-hms:compileReleaseLibraryResources' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/macos/Documents/GitHub/reactnative_meradoc'. Reason: Task ':app:bundleReleaseJsAndAssets' uses this output of task ':100mslive_react-native-hms:compileReleaseRenderscript' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/macos/Documents/GitHub/reactnative_meradoc'. Reason: Task ':app:bundleReleaseJsAndAssets' uses this output of task ':100mslive_react-native-hms:generateReleaseResValues' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/macos/Documents/GitHub/reactnative_meradoc'. Reason: Task ':app:bundleReleaseJsAndAssets' uses this output of task ':100mslive_react-native-hms:packageReleaseResources' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/macos/Documents/GitHub/reactnative_meradoc'. Reason: Task ':app:bundleReleaseJsAndAssets' uses this output of task ':@100mslive_react-native-hms:compileReleaseLibraryResources' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/macos/Documents/GitHub/reactnative_meradoc'. Reason: Task ':app:bundleReleaseJsAndAssets' uses this output of task ':@100mslive_react-native-hms:compileReleaseRenderscript' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/macos/Documents/GitHub/reactnative_meradoc'. Reason: Task ':app:bundleReleaseJsAndAssets' uses this output of task ':@100mslive_react-native-hms:generateReleaseResValues' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/macos/Documents/GitHub/reactnative_meradoc'. Reason: Task ':app:bundleReleaseJsAndAssets' uses this output of task ':@100mslive_react-native-hms:packageReleaseResources' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.
warning: the transform cache was reset.
                    Welcome to Metro!
              Fast - Scalable - Integrated


watchman warning:  Recrawled this watch 1 time, most recently because:
MustScanSubDirs UserDroppedTo resolve, please review the information on
https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
To clear this warning, run:
`watchman watch-del '/Users/macos/Documents/GitHub/reactnative_meradoc' ; watchman watch-project '/Users/macos/Documents/GitHub/reactnative_meradoc'`

Recrawled this watch 1 time, most recently because:
MustScanSubDirs UserDroppedTo resolve, please review the information on
https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
To clear this warning, run:
`watchman watch-del '/Users/macos/Documents/GitHub/reactnative_meradoc' ; watchman watch-project '/Users/macos/Documents/GitHub/reactnative_meradoc'`

Recrawled this watch 1 time, most recently because:
MustScanSubDirs UserDroppedTo resolve, please review the information on
https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
To clear this warning, run:
`watchman watch-del '/Users/macos/Documents/GitHub/reactnative_meradoc' ; watchman watch-project '/Users/macos/Documents/GitHub/reactnative_meradoc'`

Failed to construct transformer:  Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:79:19)
    at Object.createHash (node:crypto:139:10)
    at stableHash (/Users/macos/Documents/GitHub/reactnative_meradoc/node_modules/metro-cache/src/stableHash.js:19:8)
    at Object.getCacheKey (/Users/macos/Documents/GitHub/reactnative_meradoc/node_modules/metro-transform-worker/src/index.js:593:7)
    at getTransformCacheKey (/Users/macos/Documents/GitHub/reactnative_meradoc/node_modules/metro/src/DeltaBundler/getTransformCacheKey.js:24:19)
    at new Transformer (/Users/macos/Documents/GitHub/reactnative_meradoc/node_modules/metro/src/DeltaBundler/Transformer.js:48:9)
    at /Users/macos/Documents/GitHub/reactnative_meradoc/node_modules/metro/src/Bundler.js:22:29
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  opensslErrorStack: [
    'error:03000086:digital envelope routines::initialization error',
    'error:0308010C:digital envelope routines::unsupported'
  ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
error Cannot read properties of undefined (reading 'transformFile').
TypeError: Cannot read properties of undefined (reading 'transformFile')
    at Bundler.transformFile (/Users/macos/Documents/GitHub/reactnative_meradoc/node_modules/metro/src/Bundler.js:48:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.transform (/Users/macos/Documents/GitHub/reactnative_meradoc/node_modules/metro/src/lib/transformHelpers.js:101:12)
    at async processModule (/Users/macos/Documents/GitHub/reactnative_meradoc/node_modules/metro/src/DeltaBundler/traverseDependencies.js:137:18)
    at async traverseDependenciesForSingleFile (/Users/macos/Documents/GitHub/reactnative_meradoc/node_modules/metro/src/DeltaBundler/traverseDependencies.js:131:3)
    at async Promise.all (index 0)
    at async initialTraverseDependencies (/Users/macos/Documents/GitHub/reactnative_meradoc/node_modules/metro/src/DeltaBundler/traverseDependencies.js:114:3)
    at async DeltaCalculator._getChangedDependencies (/Users/macos/Documents/GitHub/reactnative_meradoc/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:164:25)
    at async DeltaCalculator.getDelta (/Users/macos/Documents/GitHub/reactnative_meradoc/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:94:16)
    at async DeltaBundler.buildGraph (/Users/macos/Documents/GitHub/reactnative_meradoc/node_modules/metro/src/DeltaBundler.js:50:5)
info Run CLI with --verbose flag for more details.

> Task :app:bundleReleaseJsAndAssets FAILED

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'node'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':100mslive_react-native-hms:compileReleaseLibraryResources'.
> A failure occurred while executing com.android.build.gradle.tasks.CompileLibraryResourcesTask$CompileLibraryResourcesAction
   > There were multiple failures while executing work items
      > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
         > Android resource compilation failed
           ERROR:AAPT: /Users/macos/Documents/GitHub/reactnative_meradoc/node_modules/@100mslive/react-native-hms/android/build/intermediates/packaged_res/release/drawable-ldpi-v4/ic_camera_toggle_on.png: error: file not found.
           
               
      > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
         > Android resource compilation failed
           ERROR:AAPT: /Users/macos/Documents/GitHub/reactnative_meradoc/node_modules/@100mslive/react-native-hms/android/build/intermediates/packaged_res/release/drawable-mdpi-v4/ic_camera_toggle_on.png: error: file not found.
           
               
      > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
         > Android resource compilation failed
           ERROR:AAPT: /Users/macos/Documents/GitHub/reactnative_meradoc/node_modules/@100mslive/react-native-hms/android/build/intermediates/packaged_res/release/drawable-hdpi-v4/ic_camera_toggle_on.png: error: file not found.
           
               
      > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
         > Android resource compilation failed
           ERROR:AAPT: /Users/macos/Documents/GitHub/reactnative_meradoc/node_modules/@100mslive/react-native-hms/android/build/intermediates/packaged_res/release/drawable-ldpi-v4/ic_camera_toggle_off.png: error: file not found.
           
               
      > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
         > Android resource compilation failed
           ERROR:AAPT: /Users/macos/Documents/GitHub/reactnative_meradoc/node_modules/@100mslive/react-native-hms/android/build/intermediates/packaged_res/release/drawable-mdpi-v4/ic_camera_toggle_off.png: error: file not found.
           
               
      > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
         > Android resource compilation failed
           ERROR:AAPT: /Users/macos/Documents/GitHub/reactnative_meradoc/node_modules/@100mslive/react-native-hms/android/build/intermediates/packaged_res/release/drawable-xhdpi-v4/ic_camera_toggle_on.png: error: file not found.
           
               
      > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
         > Android resource compilation failed
           ERROR:AAPT: /Users/macos/Documents/GitHub/reactnative_meradoc/node_modules/@100mslive/react-native-hms/android/build/intermediates/packaged_res/release/drawable-xxhdpi-v4/ic_camera_toggle_on.png: error: file not found.
           
               
      > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
         > Android resource compilation failed
           ERROR:AAPT: /Users/macos/Documents/GitHub/reactnative_meradoc/node_modules/@100mslive/react-native-hms/android/build/intermediates/packaged_res/release/drawable-hdpi-v4/ic_camera_toggle_off.png: error: file not found.
           
               

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 2 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.


```

</details>

**Comment by ygit** [comment]
@silenteyesoncode Can you share your `Node` version & `gradle-wrapper.properties` file?
